# -*- coding: utf-8 -*-
"""tp2_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BDNm0Vcy7faK7RCKFOMO8YePQ_3qYPQ

1-Faça um programa, utilizando a estrutura FOR, que imprima na tela apenas os números ímpares entre 1 e 50.
"""

for i in range(1, 51):
    if i % 2 != 0:
        print(i)

"""------------------------------------------------------------------------------

2-Suponhamos que a população de um país A seja de 80.000 habitantes, com uma taxa anual de crescimento de 3%, e que a população de B seja 200.000 habitantes, com uma taxa de crescimento de 1.5%. Faça um programa, utilizando a estrutura WHILE, que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento.
"""

a = 80000
b = 200000
cont = 0
while a<b:
  a += a * 0.3
  b += b * 0.15
  cont+= 1
print(f"Anos necessários: {cont}")

"""---

3-Escreva um programa que receba do usuário uma sequência de números inteiros separados por vírgulas e gere uma lista contendo todos os números fornecidos.
Exemplo: seja a entrada 34,67,55,33,12,98.
A saída será: ['34', '67', '55', '33', '12', '98']
Dica: pesquise sobre o método 'split'. Ele será útil para separar os números da entrada.
"""

numeros = input("Entre com números inteiros separados por vírgula: ")
lista = numeros.split(",")

print(f"Saída: {lista}")

"""---

4-Faça um programa que receba uma lista com 10 números inteiros do usuário, calcule e mostre a soma dos quadrados dos elementos da lista.
"""

x = 0
lista = []
while x < 10:
  n = int(input(f"Digite o {x+1}º número: "))
  lista.append(n)
  x+=1
soma_quadrados = sum(x ** 2 for x in lista)
print(f"Soma dos quadrados da lista: {soma_quadrados}")

"""---

5-Faça um programa que peça a entrada de um número inteiro pelo usuário e retorne o próprio número, seu quadrado e sua raiz quadrada. Utilize uma única função para executar todas as operações e calcule a raiz quadrada sem a ajuda de bibliotecas externas.
"""

def calcular():
  n = int(input("Entre com um número inteiro: "))
  n_quadrado = n * n
  raiz_quadrada = n
  margem_erro = 0.0000
  while abs( raiz_quadrada* raiz_quadrada - n) > margem_erro:
      raiz_quadrada = (raiz_quadrada + n / raiz_quadrada) / 2


  print(f"\n Número digitado: {n}\n {n} ao quadrado: {n_quadrado}\n Raiz quadrada de {n}: {raiz_quadrada} ")

calcular()

"""---

6-Faça um programa que peça a entrada de dois números inteiros pelo usuário e retorne a soma, subtração do primeiro pelo segundo, multiplicação, divisão do primeiro pelo segundo número e resto da divisão do primeiro pelo segundo número. Utilize uma única função para executar todas as operações.
"""

def operacoes():
  n1 = int(input("Entre com um número inteiro: "))
  n2 = int(input("Entre com outro numero inteiro: "))
  soma = n1 + n2
  subtracao = n1 - n2
  multiplicacao = n1 * n2
  divisao = n1/n2
  resto_divisao = divisao % 2

  print(f"\n Soma:{soma}\n Subtração:{subtracao}\n Multiplicacao: {multiplicacao}\n Divisao: {divisao}\n Resto da divisão: {resto_divisao}" )
  return
operacoes()

"""---

7-Faça um programa com uma função chamada ‘inclui_imposto’. A função possui dois parâmetros formais: ‘taxa’, que é a quantia de imposto sobre vendas expressa em porcentagem e ‘custo’, que é o custo de um item antes do imposto. A função deve receber um valor informado pelo usuário para a taxa e o custo e retornar o valor do item já adicionado do imposto. Caso não seja fornecida uma taxa, utilize a taxa padrão de 5%.
"""

def inclui_imposto(taxa, custo):
  taxa = float(taxa)
  custo = float(custo)

  if taxa == 0:
        valor_final = 0.05 * custo + custo
  else:
        valor_final = taxa * custo / 100 + custo

  return valor_final

def main():
  taxa = input("Valor da taxa em porcentagem: ")
  custo = input("Valor do custo: ")
  print(f"Valor total {inclui_imposto(taxa, custo)}")
main()

"""---

8-Pegue a função criada na questão 7 e documente-a através do recurso de docstring. Apresente a documentação criada para a função utilizando a função apropriada do Python.
"""

def inclui_imposto(taxa, custo):
    """
    Calcula o valor total de um item com imposto incluído.

    Parâmetros:
        taxa (float): A taxa de imposto sobre vendas em porcentagem.
        custo (float): O custo do item antes do imposto.

    Retorna:
        float: O valor total do item após adicionar o imposto.

    Exemplo:
        >>> inclui_imposto(10, 100)
        110.0
        >>> inclui_imposto(0, 100)
        105.0
    """
    taxa = float(taxa)
    custo = float(custo)

    if taxa == 0:
        valor_final = 0.05 * custo + custo
    else:
        valor_final = taxa * custo / 100 + custo

    return valor_final


print(inclui_imposto.__doc__)