# -*- coding: utf-8 -*-
"""nayanda_robers_DR4_TP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAgAH4-QcD1xYvs__Xyo3gDyRYxwGiHj

O site “https://archive.ics.uci.edu/dataset/1/abalone” apresenta todas as informações relacionadas a um conjunto de dados chamado Abalone (moluscos gastrópodes marinhos, presentes em águas costeiras de quase todo o mundo. Na gastronomia, o abalone é um molusco valorizado em países asiáticos).

Utilize a biblioteca Pandas em linguagem Python para carregar a base que está no link “https://github.com/jbrownlee/Datasets/blob/master/abalone.csv”, diretamente do link fornecido. Aplique todos os ajustes necessários para que a base seja carregada com os nomes de colunas corretos e presentes. Apresente sua base carregada e ajustada.

A partir da base carregada na questão 01, apresente em um dataframe único a média das variáveis “Length”, “Diameter”, “Height”, “Whole weight” e “Rings”, agrupadas pela variável “Sex”.

Utilize a biblioteca Pandas em linguagem Python para carregar a base que está aqui (lembre-se de inspecionar o arquivo para utilizar a instrução de importação de forma que funcione corretamente). Faça a importação diretamente do Github, armazene os dados em um dataframe e apresente este dataframe.

Utilize a biblioteca Pandas em linguagem Python para carregar a base que está no link “https://raw.githubusercontent.com/domoritz/maps/master/data/iris.json”, diretamente do link fornecido. A partir da base carregada, apresente a média e a mediana das quatro variáveis numéricas, por espécie de flor Iris.
"""

import pandas as pd

url_abalone = "https://github.com/jbrownlee/Datasets/raw/master/abalone.csv"
column_names = [
    "Sex", "Length", "Diameter", "Height",
    "Whole weight", "Shucked weight", "Viscera weight",
    "Shell weight", "Rings"
]
abalone_data = pd.read_csv(url_abalone, header=None, names=column_names)
print(f"Base de dados Abalone carregada e ajustada:\n{abalone_data}")


mean_values_by_sex = abalone_data.groupby('Sex')[["Length", "Diameter", "Height", "Whole weight", "Rings"]].mean()
print(f"Médias das variáveis por Sex:\n {mean_values_by_sex}")


url_iris = "https://raw.githubusercontent.com/domoritz/maps/master/data/iris.json"
iris_data = pd.read_json(url_iris)
print(f"Base de dados Iris carregada:\n{iris_data}")


mean_values_by_species = iris_data.groupby('species').mean()
median_values_by_species = iris_data.groupby('species').median()
print(f"Médias por espécie de flor Iris:\n{mean_values_by_species}")

print(f"Medianas por espécie de flor Iris:\n{median_values_by_species}")