# -*- coding: utf-8 -*-
"""nayanda_robers_DR2_TP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13L-Y7zMya9af-4xXQ9LIoMqIYEf8kf7C

#Crie um programa que peça ao usuário para inserir dois números e, em seguida, calcule e exiba a soma, subtração, multiplicação, divisão e divisão inteira desses números.
"""

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
soma = num1 + num2
subtracao = num1 - num2
multiplicacao = num1 * num2
divisao = num1 / num2
divisao_inteira = num1 // num2
print("Soma:", soma)
print("Subtração:", subtracao)
print("Multiplicação:", multiplicacao)
print("Divisão:", divisao)
print("Divisão inteira:", divisao_inteira)

"""#Faça um programa que converta um número fornecido de minutos em horas e minutos, e depois faça o inverso, convertendo horas e minutos de volta para minutos totais."""

minutos = int(input("Digite a quantidade de minutos: "))
horas = minutos // 60
minutos_restantes = minutos % 60
print(f"{minutos} minutos equivalem a {horas} horas e {minutos_restantes}")
horas2 = int(input("Digite a quantidade de horas: "))
minutos2 = int(input(f"Digite a quantidade de minutos: "))
minutos_totais = horas2 * 60 + minutos2
print(f"{horas2} horas e {minutos2} minutos equivalem a {minutos_totais} minutos totais.")

"""#Escreva um programa que receba dois nomes de usuário e os combine de maneira criativa para formar um novo nome."""

nome1 = input("Digite o primeiro nome: ")
nome2 = input("Digite o segundo nome: ")
metade_nome1 = nome1[:len(nome1) // 2]
metade_nome2 = nome2[:len(nome2) // 2]
combinacao_criativa = metade_nome1 + metade_nome2
print(f"Nome combinado: {combinacao_criativa}")

"""#Desenvolva um programa que peça ao usuário para escolher uma operação (adição, subtração, multiplicação, divisão) e dois números, e então execute a operação escolhida com os números.

"""

operacao = input("Escolha uma operação ('+' '-' '*' '/'): ")
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
resultado = 0

if operacao == "+":
    resultado = num1 + num2

elif operacao == "-":
    resultado = num1 - num2

elif operacao == "*":
    resultado = num1 * num2

elif operacao == "/":
    resultado = num1 / num2

print(f"{num1} {operacao} {num2} = {resultado}")

"""#Crie um programa que peça ao usuário seu nome e sobrenome usando input e, em seguida, combine-os para formar uma saudação personalizada.

"""

nome = input("Digite seu nome:")
sobrenome = input("Digite seu sobrenome:")
nome_sobrenome = nome + " " + sobrenome
print(f"Olá, {nome_sobrenome}!")

"""#Escreva um programa onde o usuário deve adivinhar um número secreto. O programa deve dizer se o palpite está correto, muito alto ou muito baixo.

"""

numero_secreto = 28

while True:
  palpite = int(input("Adivinhe o número secreto (entre 1 e 100): "))

  if palpite == 28:
    print("Parabéns! Você acertou o número secreto!")
    break

  elif palpite < numero_secreto:
    print("\nO número secreto é maior. Tente novamente.\n")


  elif palpite > numero_secreto:
    print("\nO número secreto é menor. Tente novamente.\n")

"""#Faça um programa que calcule o Índice de Massa Corporal (IMC) do usuário e forneça feedback com base no valor (por exemplo, abaixo do peso, peso normal, sobrepeso).

"""

peso = float(input("Digite o seu peso (kg): "))
altura = float(input("Digite a sua altura (metros): "))
imc = peso / (altura ** 2)
if imc < 18.5:
    print("Você está abaixo do peso.")
elif imc >= 18.5 and imc < 25:
    print("Seu peso está normal.")
else:
    print("Você está acima do peso.")

"""#Crie um programa que pergunte a idade do usuário e verifique se ele é maior de idade ou não.

"""

idade = int(input("Digite sua idade: "))

if idade<18:
  print("Você é menor de idade.")
else:
  print("Você é maior de idade.")

"""#Desenvolva um programa que aplique descontos diferentes com base no valor da compra: desconto de 10% para compras acima de R$100, 15% para compras acima de R$200, etc.

"""

valor = float(input("Digite o valor da compra: "))
if valor > 100 and valor < 200:
    desconto = (10/100) * valor
    print(f"{valor}")
    valor_com_desconto = valor - desconto
    print(f"O valor da compra com desconto é: {valor_com_desconto}")
elif valor >= 200:
  desconto = (15/100) * valor
  valor_com_desconto = valor - desconto
  print(f"O valor da compra com desconto é: {valor_com_desconto}")

"""#Escreva um programa que combine elementos aleatórios de listas diferentes (personagens, ações, locais) para criar uma história curiosa.

"""

import random

personagens = ["Nayanda" , "Lucas",  "Eduardo" , "Maria" ,"Camila"]
acoes = ["foi estudar", "teve uma overdose", "roubou um celular", "dormiu", "foi em um show"]
locais = ["no meio da rua", "no predio da faculdade", "na igreja", "no Canadá" ,"no metrô"]

def personagem():
  return random.choice(personagens)

def acao():
  return random.choice(acoes)

def local():
  return random.choice(locais)

print(f"{personagem()} {acao()} {local()}")

"""#Faça um programa que simule o lançamento de um dado. O usuário deve escolher quantos dados jogar e o programa deve exibir os resultados.

"""

import random
n = int(input("Quantos dados você deseja jogar? "))
def dado():
  return random.randint(1,6)


for i in range(1, n + 1):
  print(f"O resultado do dado {i} é: ", dado())

"""#Crie um programa que classifique as palavras inseridas pelo usuário como curtas (menos de 5 letras) ou longas (5 letras ou mais).

"""

palavra = input("Digite uma palavra: ")
tamanho = len(palavra)

if tamanho < 5:
  print("Essa palavra é curta")
else:
  print("Essa palavra é longa")

"""#Desenvolva um programa que verifique se uma palavra ou frase inserida pelo usuário é um palíndromo (lê-se igual de trás para frente).

"""

palavra = input("Digite uma palavra ou frase: ")
palavra = palavra.lower()
palavra = palavra.replace(" ", "")
inverso = palavra[::-1]
print(f"Palavra invertida: {inverso} " )

if palavra == inverso:
  print("Essa palavra é um palíndromo")

else:
  print("Essa palavra não é um palíndromo")

"""#Escreva um programa que permita ao usuário votar em três opções diferentes e, no final, exiba o número de votos de cada opção.

"""

opcao1 = 0
opcao2 = 0
opcao3 = 0

while True:
  print("Qual sua música favorita do album Faith in the Future de Louis Tomlinson?")
  voto = int(input(" 1- Silver Tongues \n 2- Angels Fly \n 3- High in California\n"))
  resultado = int(input(" 4- Votar novamente \n 5- Encerrar a votação e ver resultado\n"))

  if voto == 1:
    opcao1 = opcao1 + 1

  elif voto == 2:
    opcao2 = opcao2 + 1

  elif voto == 3:
    opcao3 = opcao3 + 1

  if resultado ==5:
    break

print(f"Votos para a música Silver Tongues: {opcao1}")
print(f"Votos para a música Angels Fly: {opcao2}")
print(f"Votos para a música High in California: {opcao3}")

"""#Crie um programa que apresente ao usuário uma série de escolhas (como em uma história) e conduza a diferentes resultados com base nessas escolhas.

"""

print("Você está em uma festa com seus amigos. O que você gostaria de fazer?")
print("1. Dançar a noite toda.")
print("2. Beber muito.")
print("3. Usar drogas oferecidas por um estranho.")

escolha = input("Escolha o número da sua opção: ")

if escolha == "1":
    print("\nVocê dançou a noite toda e se divertiu muito. Parabéns, você aproveitou a festa!")
elif escolha == "2":
    print("\nVocê bebeu muito, mas lembrou que veio dirigindo.")
    print("O que você faz?")
    print("1. Volta pra casa dirigindo.")
    print("2. Chama um uber.")

    escolha = input("Escolha o número da sua opção: ")

    if escolha == "1":
        print("\nVocê voltou dirigindo bêbado, sofreu um acidente e morreu")
    elif escolha == "2":
        print("\nVocê chamou um uber e chegou em casa em segurança. Parabéns!")


elif escolha == "3":
    print("\nVocê experimentou drogas oferecidas por um estranho e se sentiu mal.")
    print("O que você faz?")
    print("1. Continua usando mais drogas.")
    print("2. Pede ajuda a alguém na festa.")

    escolha = input("Escolha o número da sua opção: ")

    if escolha == "1":
        print("\nVocê continuou usando drogas, teve uma overdose e morreu.")
    elif escolha == "2":
        print("\nVocê pediu ajuda a alguém na festa, que chamou uma ambulância. Você recebeu tratamento e está bem. Parabéns!")